### ISSUE TITLE
Return key not copying query to clipboard

### ISSUE THREAD

**Issue by astratagem** [deanishe/alfred-gifs#2]
I've installed this workflow and updated it using Fixum. The open in browser and copy Markdown actions are working as they should, but the default "Copy to clipboard" isn't working when I press return. Any ideas why?

**Comment by astratagem** [comment]
It looks like Fixum removes `valid=True` from this line:

https://github.com/deanishe/alfred-gifs/blob/c379d105b536d8a42a756635b66386bb86e47ee5/src/gifs.py#L96

I added that back in and the script works properly.

**Comment by deanishe** [comment]
I'm pretty sure I messed it up at some point. Fixed in [v1.1](https://github.com/deanishe/alfred-gifs/releases/tag/v1.1). Enter `gif workflow:update` to install the update directly from Alfred.

**Comment by astratagem** [comment]
That worked, thanks!
